# --- Layout do gerador de senha --- #
<LayoutGeradorSenha>:
    orientation: 'vertical'
    padding: 20
    spacing: 20

    # --- Campo de texto onde aparecerá a senha --- #
    Label:
        text: 'Sua senha aparecerá aqui'
        font_size: '20sp'
        size_hint_y: None
        height: '50dp'

    # --- Botão para gerar a senha --- #
    Button:
        text: 'Gerar senha'
        size_hint_y: None
        height: '50dp'